/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites.index'
import { Route as AuthenticatedSitesNewRouteImport } from './routes/_authenticated/sites.new'
import { Route as AuthenticatedOnboardingWelcomeRouteImport } from './routes/_authenticated/onboarding.welcome'
import { Route as AuthenticatedOnboardingSiteRouteImport } from './routes/_authenticated/onboarding.site'
import { Route as AuthenticatedOnboardingDoneRouteImport } from './routes/_authenticated/onboarding.done'
import { Route as AuthenticatedOnboardingBusinessRouteImport } from './routes/_authenticated/onboarding.business'
import { Route as AuthenticatedAuditsAuditIdRouteImport } from './routes/_authenticated/audits.$auditId'
import { Route as ApiPublicWpcomCallbackRouteImport } from './routes/api/public/wpcom/callback'
import { Route as AuthenticatedSitesSiteIdAuditsRouteImport } from './routes/_authenticated/sites.$siteId.audits'
import { Route as AuthenticatedAuditsAuditIdProposalsRouteImport } from './routes/_authenticated/audits.$auditId_.proposals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesNewRoute = AuthenticatedSitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingWelcomeRoute =
  AuthenticatedOnboardingWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingSiteRoute =
  AuthenticatedOnboardingSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingDoneRoute =
  AuthenticatedOnboardingDoneRouteImport.update({
    id: '/done',
    path: '/done',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingBusinessRoute =
  AuthenticatedOnboardingBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAuditsAuditIdRoute =
  AuthenticatedAuditsAuditIdRouteImport.update({
    id: '/audits/$auditId',
    path: '/audits/$auditId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicWpcomCallbackRoute = ApiPublicWpcomCallbackRouteImport.update({
  id: '/api/public/wpcom/callback',
  path: '/api/public/wpcom/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesSiteIdAuditsRoute =
  AuthenticatedSitesSiteIdAuditsRouteImport.update({
    id: '/sites/$siteId/audits',
    path: '/sites/$siteId/audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditsAuditIdProposalsRoute =
  AuthenticatedAuditsAuditIdProposalsRouteImport.update({
    id: '/audits/$auditId_/proposals',
    path: '/audits/$auditId/proposals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/audits/$auditId/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/audits/$auditId/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/_authenticated/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/_authenticated/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/_authenticated/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/_authenticated/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/_authenticated/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/_authenticated/sites/new': typeof AuthenticatedSitesNewRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/audits/$auditId_/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/_authenticated/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/onboarding'
    | '/audits/$auditId'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/site'
    | '/onboarding/welcome'
    | '/sites/new'
    | '/sites/'
    | '/audits/$auditId/proposals'
    | '/sites/$siteId/audits'
    | '/api/public/wpcom/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/onboarding'
    | '/audits/$auditId'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/site'
    | '/onboarding/welcome'
    | '/sites/new'
    | '/sites'
    | '/audits/$auditId/proposals'
    | '/sites/$siteId/audits'
    | '/api/public/wpcom/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/onboarding'
    | '/_authenticated/audits/$auditId'
    | '/_authenticated/onboarding/business'
    | '/_authenticated/onboarding/done'
    | '/_authenticated/onboarding/site'
    | '/_authenticated/onboarding/welcome'
    | '/_authenticated/sites/new'
    | '/_authenticated/sites/'
    | '/_authenticated/audits/$auditId_/proposals'
    | '/_authenticated/sites/$siteId/audits'
    | '/api/public/wpcom/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiPublicWpcomCallbackRoute: typeof ApiPublicWpcomCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/new': {
      id: '/_authenticated/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AuthenticatedSitesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/welcome': {
      id: '/_authenticated/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthenticatedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/site': {
      id: '/_authenticated/onboarding/site'
      path: '/site'
      fullPath: '/onboarding/site'
      preLoaderRoute: typeof AuthenticatedOnboardingSiteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/done': {
      id: '/_authenticated/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AuthenticatedOnboardingDoneRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/business': {
      id: '/_authenticated/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/audits/$auditId': {
      id: '/_authenticated/audits/$auditId'
      path: '/audits/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/wpcom/callback': {
      id: '/api/public/wpcom/callback'
      path: '/api/public/wpcom/callback'
      fullPath: '/api/public/wpcom/callback'
      preLoaderRoute: typeof ApiPublicWpcomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/$siteId/audits': {
      id: '/_authenticated/sites/$siteId/audits'
      path: '/sites/$siteId/audits'
      fullPath: '/sites/$siteId/audits'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits/$auditId_/proposals': {
      id: '/_authenticated/audits/$auditId_/proposals'
      path: '/audits/$auditId/proposals'
      fullPath: '/audits/$auditId/proposals'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBusinessRoute: typeof AuthenticatedOnboardingBusinessRoute
  AuthenticatedOnboardingDoneRoute: typeof AuthenticatedOnboardingDoneRoute
  AuthenticatedOnboardingSiteRoute: typeof AuthenticatedOnboardingSiteRoute
  AuthenticatedOnboardingWelcomeRoute: typeof AuthenticatedOnboardingWelcomeRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBusinessRoute: AuthenticatedOnboardingBusinessRoute,
    AuthenticatedOnboardingDoneRoute: AuthenticatedOnboardingDoneRoute,
    AuthenticatedOnboardingSiteRoute: AuthenticatedOnboardingSiteRoute,
    AuthenticatedOnboardingWelcomeRoute: AuthenticatedOnboardingWelcomeRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedAuditsAuditIdRoute: typeof AuthenticatedAuditsAuditIdRoute
  AuthenticatedSitesNewRoute: typeof AuthenticatedSitesNewRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedAuditsAuditIdProposalsRoute: typeof AuthenticatedAuditsAuditIdProposalsRoute
  AuthenticatedSitesSiteIdAuditsRoute: typeof AuthenticatedSitesSiteIdAuditsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedAuditsAuditIdRoute: AuthenticatedAuditsAuditIdRoute,
  AuthenticatedSitesNewRoute: AuthenticatedSitesNewRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedAuditsAuditIdProposalsRoute:
    AuthenticatedAuditsAuditIdProposalsRoute,
  AuthenticatedSitesSiteIdAuditsRoute: AuthenticatedSitesSiteIdAuditsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiPublicWpcomCallbackRoute: ApiPublicWpcomCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
