/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RShareTokenRouteImport } from './routes/r.$shareToken'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedSitesIndexRouteImport } from './routes/_authenticated/sites.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as ApiPublicRunAnalyzerJobRouteImport } from './routes/api/public/run-analyzer-job'
import { Route as ApiPublicLeadIngestRouteImport } from './routes/api/public/lead-ingest'
import { Route as AuthenticatedSitesNewRouteImport } from './routes/_authenticated/sites.new'
import { Route as AuthenticatedSettingsToneProfileRouteImport } from './routes/_authenticated/settings.tone-profile'
import { Route as AuthenticatedSettingsGrowthGoalRouteImport } from './routes/_authenticated/settings.growth-goal'
import { Route as AuthenticatedSettingsBusinessProfileRouteImport } from './routes/_authenticated/settings.business-profile'
import { Route as AuthenticatedOnboardingWelcomeRouteImport } from './routes/_authenticated/onboarding.welcome'
import { Route as AuthenticatedOnboardingSiteRouteImport } from './routes/_authenticated/onboarding.site'
import { Route as AuthenticatedOnboardingDoneRouteImport } from './routes/_authenticated/onboarding.done'
import { Route as AuthenticatedOnboardingBusinessRouteImport } from './routes/_authenticated/onboarding.business'
import { Route as AuthenticatedGrowthReportsRouteImport } from './routes/_authenticated/growth.reports'
import { Route as AuthenticatedGrowthMonthlyPlanRouteImport } from './routes/_authenticated/growth.monthly-plan'
import { Route as AuthenticatedGrowthMasterplanRouteImport } from './routes/_authenticated/growth.masterplan'
import { Route as AuthenticatedGrowthLeadsRouteImport } from './routes/_authenticated/growth.leads'
import { Route as AuthenticatedGrowthIntelligenceRouteImport } from './routes/_authenticated/growth.intelligence'
import { Route as AuthenticatedGrowthGbpRouteImport } from './routes/_authenticated/growth.gbp'
import { Route as AuthenticatedGrowthFlowRouteImport } from './routes/_authenticated/growth.flow'
import { Route as AuthenticatedGrowthExecutionRouteImport } from './routes/_authenticated/growth.execution'
import { Route as AuthenticatedGrowthBlueprintRouteImport } from './routes/_authenticated/growth.blueprint'
import { Route as AuthenticatedClientsTenantIdRouteImport } from './routes/_authenticated/clients.$tenantId'
import { Route as AuthenticatedAuditsAuditIdRouteImport } from './routes/_authenticated/audits.$auditId'
import { Route as AuthenticatedClientsTenantIdIndexRouteImport } from './routes/_authenticated/clients.$tenantId.index'
import { Route as ApiPublicWpcomCallbackRouteImport } from './routes/api/public/wpcom/callback'
import { Route as AuthenticatedSitesSiteIdInventoryRouteImport } from './routes/_authenticated/sites.$siteId.inventory'
import { Route as AuthenticatedSitesSiteIdAuditsRouteImport } from './routes/_authenticated/sites.$siteId.audits'
import { Route as AuthenticatedClientsTenantIdSettingsRouteImport } from './routes/_authenticated/clients.$tenantId.settings'
import { Route as AuthenticatedClientsTenantIdReportsRouteImport } from './routes/_authenticated/clients.$tenantId.reports'
import { Route as AuthenticatedClientsTenantIdPagesRouteImport } from './routes/_authenticated/clients.$tenantId.pages'
import { Route as AuthenticatedClientsTenantIdOverviewRouteImport } from './routes/_authenticated/clients.$tenantId.overview'
import { Route as AuthenticatedClientsTenantIdLeadsRouteImport } from './routes/_authenticated/clients.$tenantId.leads'
import { Route as AuthenticatedClientsTenantIdExecutionRouteImport } from './routes/_authenticated/clients.$tenantId.execution'
import { Route as AuthenticatedAuditsAuditIdProposalsRouteImport } from './routes/_authenticated/audits.$auditId_.proposals'
import { Route as AuthenticatedAuditsAuditIdCompareRouteImport } from './routes/_authenticated/audits.$auditId_.compare'
import { Route as AuthenticatedGrowthMasterplanItemIdProposalsRouteImport } from './routes/_authenticated/growth.masterplan_.$itemId.proposals'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RShareTokenRoute = RShareTokenRouteImport.update({
  id: '/r/$shareToken',
  path: '/r/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesIndexRoute = AuthenticatedSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicRunAnalyzerJobRoute = ApiPublicRunAnalyzerJobRouteImport.update({
  id: '/api/public/run-analyzer-job',
  path: '/api/public/run-analyzer-job',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadIngestRoute = ApiPublicLeadIngestRouteImport.update({
  id: '/api/public/lead-ingest',
  path: '/api/public/lead-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesNewRoute = AuthenticatedSitesNewRouteImport.update({
  id: '/sites/new',
  path: '/sites/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsToneProfileRoute =
  AuthenticatedSettingsToneProfileRouteImport.update({
    id: '/settings/tone-profile',
    path: '/settings/tone-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsGrowthGoalRoute =
  AuthenticatedSettingsGrowthGoalRouteImport.update({
    id: '/settings/growth-goal',
    path: '/settings/growth-goal',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsBusinessProfileRoute =
  AuthenticatedSettingsBusinessProfileRouteImport.update({
    id: '/settings/business-profile',
    path: '/settings/business-profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingWelcomeRoute =
  AuthenticatedOnboardingWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingSiteRoute =
  AuthenticatedOnboardingSiteRouteImport.update({
    id: '/site',
    path: '/site',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingDoneRoute =
  AuthenticatedOnboardingDoneRouteImport.update({
    id: '/done',
    path: '/done',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingBusinessRoute =
  AuthenticatedOnboardingBusinessRouteImport.update({
    id: '/business',
    path: '/business',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedGrowthReportsRoute =
  AuthenticatedGrowthReportsRouteImport.update({
    id: '/growth/reports',
    path: '/growth/reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthMonthlyPlanRoute =
  AuthenticatedGrowthMonthlyPlanRouteImport.update({
    id: '/growth/monthly-plan',
    path: '/growth/monthly-plan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthMasterplanRoute =
  AuthenticatedGrowthMasterplanRouteImport.update({
    id: '/growth/masterplan',
    path: '/growth/masterplan',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthLeadsRoute =
  AuthenticatedGrowthLeadsRouteImport.update({
    id: '/growth/leads',
    path: '/growth/leads',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthIntelligenceRoute =
  AuthenticatedGrowthIntelligenceRouteImport.update({
    id: '/growth/intelligence',
    path: '/growth/intelligence',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthGbpRoute = AuthenticatedGrowthGbpRouteImport.update({
  id: '/growth/gbp',
  path: '/growth/gbp',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthFlowRoute = AuthenticatedGrowthFlowRouteImport.update({
  id: '/growth/flow',
  path: '/growth/flow',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGrowthExecutionRoute =
  AuthenticatedGrowthExecutionRouteImport.update({
    id: '/growth/execution',
    path: '/growth/execution',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthBlueprintRoute =
  AuthenticatedGrowthBlueprintRouteImport.update({
    id: '/growth/blueprint',
    path: '/growth/blueprint',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsTenantIdRoute =
  AuthenticatedClientsTenantIdRouteImport.update({
    id: '/clients/$tenantId',
    path: '/clients/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditsAuditIdRoute =
  AuthenticatedAuditsAuditIdRouteImport.update({
    id: '/audits/$auditId',
    path: '/audits/$auditId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsTenantIdIndexRoute =
  AuthenticatedClientsTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const ApiPublicWpcomCallbackRoute = ApiPublicWpcomCallbackRouteImport.update({
  id: '/api/public/wpcom/callback',
  path: '/api/public/wpcom/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSitesSiteIdInventoryRoute =
  AuthenticatedSitesSiteIdInventoryRouteImport.update({
    id: '/sites/$siteId/inventory',
    path: '/sites/$siteId/inventory',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSitesSiteIdAuditsRoute =
  AuthenticatedSitesSiteIdAuditsRouteImport.update({
    id: '/sites/$siteId/audits',
    path: '/sites/$siteId/audits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsTenantIdSettingsRoute =
  AuthenticatedClientsTenantIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedClientsTenantIdReportsRoute =
  AuthenticatedClientsTenantIdReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedClientsTenantIdPagesRoute =
  AuthenticatedClientsTenantIdPagesRouteImport.update({
    id: '/pages',
    path: '/pages',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedClientsTenantIdOverviewRoute =
  AuthenticatedClientsTenantIdOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedClientsTenantIdLeadsRoute =
  AuthenticatedClientsTenantIdLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedClientsTenantIdExecutionRoute =
  AuthenticatedClientsTenantIdExecutionRouteImport.update({
    id: '/execution',
    path: '/execution',
    getParentRoute: () => AuthenticatedClientsTenantIdRoute,
  } as any)
const AuthenticatedAuditsAuditIdProposalsRoute =
  AuthenticatedAuditsAuditIdProposalsRouteImport.update({
    id: '/audits/$auditId_/proposals',
    path: '/audits/$auditId/proposals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditsAuditIdCompareRoute =
  AuthenticatedAuditsAuditIdCompareRouteImport.update({
    id: '/audits/$auditId_/compare',
    path: '/audits/$auditId/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGrowthMasterplanItemIdProposalsRoute =
  AuthenticatedGrowthMasterplanItemIdProposalsRouteImport.update({
    id: '/growth/masterplan_/$itemId/proposals',
    path: '/growth/masterplan/$itemId/proposals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/r/$shareToken': typeof RShareTokenRoute
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/clients/$tenantId': typeof AuthenticatedClientsTenantIdRouteWithChildren
  '/growth/blueprint': typeof AuthenticatedGrowthBlueprintRoute
  '/growth/execution': typeof AuthenticatedGrowthExecutionRoute
  '/growth/flow': typeof AuthenticatedGrowthFlowRoute
  '/growth/gbp': typeof AuthenticatedGrowthGbpRoute
  '/growth/intelligence': typeof AuthenticatedGrowthIntelligenceRoute
  '/growth/leads': typeof AuthenticatedGrowthLeadsRoute
  '/growth/masterplan': typeof AuthenticatedGrowthMasterplanRoute
  '/growth/monthly-plan': typeof AuthenticatedGrowthMonthlyPlanRoute
  '/growth/reports': typeof AuthenticatedGrowthReportsRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/settings/business-profile': typeof AuthenticatedSettingsBusinessProfileRoute
  '/settings/growth-goal': typeof AuthenticatedSettingsGrowthGoalRoute
  '/settings/tone-profile': typeof AuthenticatedSettingsToneProfileRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/api/public/lead-ingest': typeof ApiPublicLeadIngestRoute
  '/api/public/run-analyzer-job': typeof ApiPublicRunAnalyzerJobRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/sites/': typeof AuthenticatedSitesIndexRoute
  '/audits/$auditId/compare': typeof AuthenticatedAuditsAuditIdCompareRoute
  '/audits/$auditId/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/clients/$tenantId/execution': typeof AuthenticatedClientsTenantIdExecutionRoute
  '/clients/$tenantId/leads': typeof AuthenticatedClientsTenantIdLeadsRoute
  '/clients/$tenantId/overview': typeof AuthenticatedClientsTenantIdOverviewRoute
  '/clients/$tenantId/pages': typeof AuthenticatedClientsTenantIdPagesRoute
  '/clients/$tenantId/reports': typeof AuthenticatedClientsTenantIdReportsRoute
  '/clients/$tenantId/settings': typeof AuthenticatedClientsTenantIdSettingsRoute
  '/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/sites/$siteId/inventory': typeof AuthenticatedSitesSiteIdInventoryRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
  '/clients/$tenantId/': typeof AuthenticatedClientsTenantIdIndexRoute
  '/growth/masterplan/$itemId/proposals': typeof AuthenticatedGrowthMasterplanItemIdProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app': typeof AuthenticatedAppRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/r/$shareToken': typeof RShareTokenRoute
  '/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/growth/blueprint': typeof AuthenticatedGrowthBlueprintRoute
  '/growth/execution': typeof AuthenticatedGrowthExecutionRoute
  '/growth/flow': typeof AuthenticatedGrowthFlowRoute
  '/growth/gbp': typeof AuthenticatedGrowthGbpRoute
  '/growth/intelligence': typeof AuthenticatedGrowthIntelligenceRoute
  '/growth/leads': typeof AuthenticatedGrowthLeadsRoute
  '/growth/masterplan': typeof AuthenticatedGrowthMasterplanRoute
  '/growth/monthly-plan': typeof AuthenticatedGrowthMonthlyPlanRoute
  '/growth/reports': typeof AuthenticatedGrowthReportsRoute
  '/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/settings/business-profile': typeof AuthenticatedSettingsBusinessProfileRoute
  '/settings/growth-goal': typeof AuthenticatedSettingsGrowthGoalRoute
  '/settings/tone-profile': typeof AuthenticatedSettingsToneProfileRoute
  '/sites/new': typeof AuthenticatedSitesNewRoute
  '/api/public/lead-ingest': typeof ApiPublicLeadIngestRoute
  '/api/public/run-analyzer-job': typeof ApiPublicRunAnalyzerJobRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/sites': typeof AuthenticatedSitesIndexRoute
  '/audits/$auditId/compare': typeof AuthenticatedAuditsAuditIdCompareRoute
  '/audits/$auditId/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/clients/$tenantId/execution': typeof AuthenticatedClientsTenantIdExecutionRoute
  '/clients/$tenantId/leads': typeof AuthenticatedClientsTenantIdLeadsRoute
  '/clients/$tenantId/overview': typeof AuthenticatedClientsTenantIdOverviewRoute
  '/clients/$tenantId/pages': typeof AuthenticatedClientsTenantIdPagesRoute
  '/clients/$tenantId/reports': typeof AuthenticatedClientsTenantIdReportsRoute
  '/clients/$tenantId/settings': typeof AuthenticatedClientsTenantIdSettingsRoute
  '/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/sites/$siteId/inventory': typeof AuthenticatedSitesSiteIdInventoryRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
  '/clients/$tenantId': typeof AuthenticatedClientsTenantIdIndexRoute
  '/growth/masterplan/$itemId/proposals': typeof AuthenticatedGrowthMasterplanItemIdProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/r/$shareToken': typeof RShareTokenRoute
  '/_authenticated/audits/$auditId': typeof AuthenticatedAuditsAuditIdRoute
  '/_authenticated/clients/$tenantId': typeof AuthenticatedClientsTenantIdRouteWithChildren
  '/_authenticated/growth/blueprint': typeof AuthenticatedGrowthBlueprintRoute
  '/_authenticated/growth/execution': typeof AuthenticatedGrowthExecutionRoute
  '/_authenticated/growth/flow': typeof AuthenticatedGrowthFlowRoute
  '/_authenticated/growth/gbp': typeof AuthenticatedGrowthGbpRoute
  '/_authenticated/growth/intelligence': typeof AuthenticatedGrowthIntelligenceRoute
  '/_authenticated/growth/leads': typeof AuthenticatedGrowthLeadsRoute
  '/_authenticated/growth/masterplan': typeof AuthenticatedGrowthMasterplanRoute
  '/_authenticated/growth/monthly-plan': typeof AuthenticatedGrowthMonthlyPlanRoute
  '/_authenticated/growth/reports': typeof AuthenticatedGrowthReportsRoute
  '/_authenticated/onboarding/business': typeof AuthenticatedOnboardingBusinessRoute
  '/_authenticated/onboarding/done': typeof AuthenticatedOnboardingDoneRoute
  '/_authenticated/onboarding/site': typeof AuthenticatedOnboardingSiteRoute
  '/_authenticated/onboarding/welcome': typeof AuthenticatedOnboardingWelcomeRoute
  '/_authenticated/settings/business-profile': typeof AuthenticatedSettingsBusinessProfileRoute
  '/_authenticated/settings/growth-goal': typeof AuthenticatedSettingsGrowthGoalRoute
  '/_authenticated/settings/tone-profile': typeof AuthenticatedSettingsToneProfileRoute
  '/_authenticated/sites/new': typeof AuthenticatedSitesNewRoute
  '/api/public/lead-ingest': typeof ApiPublicLeadIngestRoute
  '/api/public/run-analyzer-job': typeof ApiPublicRunAnalyzerJobRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/sites/': typeof AuthenticatedSitesIndexRoute
  '/_authenticated/audits/$auditId_/compare': typeof AuthenticatedAuditsAuditIdCompareRoute
  '/_authenticated/audits/$auditId_/proposals': typeof AuthenticatedAuditsAuditIdProposalsRoute
  '/_authenticated/clients/$tenantId/execution': typeof AuthenticatedClientsTenantIdExecutionRoute
  '/_authenticated/clients/$tenantId/leads': typeof AuthenticatedClientsTenantIdLeadsRoute
  '/_authenticated/clients/$tenantId/overview': typeof AuthenticatedClientsTenantIdOverviewRoute
  '/_authenticated/clients/$tenantId/pages': typeof AuthenticatedClientsTenantIdPagesRoute
  '/_authenticated/clients/$tenantId/reports': typeof AuthenticatedClientsTenantIdReportsRoute
  '/_authenticated/clients/$tenantId/settings': typeof AuthenticatedClientsTenantIdSettingsRoute
  '/_authenticated/sites/$siteId/audits': typeof AuthenticatedSitesSiteIdAuditsRoute
  '/_authenticated/sites/$siteId/inventory': typeof AuthenticatedSitesSiteIdInventoryRoute
  '/api/public/wpcom/callback': typeof ApiPublicWpcomCallbackRoute
  '/_authenticated/clients/$tenantId/': typeof AuthenticatedClientsTenantIdIndexRoute
  '/_authenticated/growth/masterplan_/$itemId/proposals': typeof AuthenticatedGrowthMasterplanItemIdProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/dashboard'
    | '/onboarding'
    | '/r/$shareToken'
    | '/audits/$auditId'
    | '/clients/$tenantId'
    | '/growth/blueprint'
    | '/growth/execution'
    | '/growth/flow'
    | '/growth/gbp'
    | '/growth/intelligence'
    | '/growth/leads'
    | '/growth/masterplan'
    | '/growth/monthly-plan'
    | '/growth/reports'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/site'
    | '/onboarding/welcome'
    | '/settings/business-profile'
    | '/settings/growth-goal'
    | '/settings/tone-profile'
    | '/sites/new'
    | '/api/public/lead-ingest'
    | '/api/public/run-analyzer-job'
    | '/clients/'
    | '/sites/'
    | '/audits/$auditId/compare'
    | '/audits/$auditId/proposals'
    | '/clients/$tenantId/execution'
    | '/clients/$tenantId/leads'
    | '/clients/$tenantId/overview'
    | '/clients/$tenantId/pages'
    | '/clients/$tenantId/reports'
    | '/clients/$tenantId/settings'
    | '/sites/$siteId/audits'
    | '/sites/$siteId/inventory'
    | '/api/public/wpcom/callback'
    | '/clients/$tenantId/'
    | '/growth/masterplan/$itemId/proposals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app'
    | '/dashboard'
    | '/onboarding'
    | '/r/$shareToken'
    | '/audits/$auditId'
    | '/growth/blueprint'
    | '/growth/execution'
    | '/growth/flow'
    | '/growth/gbp'
    | '/growth/intelligence'
    | '/growth/leads'
    | '/growth/masterplan'
    | '/growth/monthly-plan'
    | '/growth/reports'
    | '/onboarding/business'
    | '/onboarding/done'
    | '/onboarding/site'
    | '/onboarding/welcome'
    | '/settings/business-profile'
    | '/settings/growth-goal'
    | '/settings/tone-profile'
    | '/sites/new'
    | '/api/public/lead-ingest'
    | '/api/public/run-analyzer-job'
    | '/clients'
    | '/sites'
    | '/audits/$auditId/compare'
    | '/audits/$auditId/proposals'
    | '/clients/$tenantId/execution'
    | '/clients/$tenantId/leads'
    | '/clients/$tenantId/overview'
    | '/clients/$tenantId/pages'
    | '/clients/$tenantId/reports'
    | '/clients/$tenantId/settings'
    | '/sites/$siteId/audits'
    | '/sites/$siteId/inventory'
    | '/api/public/wpcom/callback'
    | '/clients/$tenantId'
    | '/growth/masterplan/$itemId/proposals'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/r/$shareToken'
    | '/_authenticated/audits/$auditId'
    | '/_authenticated/clients/$tenantId'
    | '/_authenticated/growth/blueprint'
    | '/_authenticated/growth/execution'
    | '/_authenticated/growth/flow'
    | '/_authenticated/growth/gbp'
    | '/_authenticated/growth/intelligence'
    | '/_authenticated/growth/leads'
    | '/_authenticated/growth/masterplan'
    | '/_authenticated/growth/monthly-plan'
    | '/_authenticated/growth/reports'
    | '/_authenticated/onboarding/business'
    | '/_authenticated/onboarding/done'
    | '/_authenticated/onboarding/site'
    | '/_authenticated/onboarding/welcome'
    | '/_authenticated/settings/business-profile'
    | '/_authenticated/settings/growth-goal'
    | '/_authenticated/settings/tone-profile'
    | '/_authenticated/sites/new'
    | '/api/public/lead-ingest'
    | '/api/public/run-analyzer-job'
    | '/_authenticated/clients/'
    | '/_authenticated/sites/'
    | '/_authenticated/audits/$auditId_/compare'
    | '/_authenticated/audits/$auditId_/proposals'
    | '/_authenticated/clients/$tenantId/execution'
    | '/_authenticated/clients/$tenantId/leads'
    | '/_authenticated/clients/$tenantId/overview'
    | '/_authenticated/clients/$tenantId/pages'
    | '/_authenticated/clients/$tenantId/reports'
    | '/_authenticated/clients/$tenantId/settings'
    | '/_authenticated/sites/$siteId/audits'
    | '/_authenticated/sites/$siteId/inventory'
    | '/api/public/wpcom/callback'
    | '/_authenticated/clients/$tenantId/'
    | '/_authenticated/growth/masterplan_/$itemId/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  RShareTokenRoute: typeof RShareTokenRoute
  ApiPublicLeadIngestRoute: typeof ApiPublicLeadIngestRoute
  ApiPublicRunAnalyzerJobRoute: typeof ApiPublicRunAnalyzerJobRoute
  ApiPublicWpcomCallbackRoute: typeof ApiPublicWpcomCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$shareToken': {
      id: '/r/$shareToken'
      path: '/r/$shareToken'
      fullPath: '/r/$shareToken'
      preLoaderRoute: typeof RShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/': {
      id: '/_authenticated/sites/'
      path: '/sites'
      fullPath: '/sites/'
      preLoaderRoute: typeof AuthenticatedSitesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/run-analyzer-job': {
      id: '/api/public/run-analyzer-job'
      path: '/api/public/run-analyzer-job'
      fullPath: '/api/public/run-analyzer-job'
      preLoaderRoute: typeof ApiPublicRunAnalyzerJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lead-ingest': {
      id: '/api/public/lead-ingest'
      path: '/api/public/lead-ingest'
      fullPath: '/api/public/lead-ingest'
      preLoaderRoute: typeof ApiPublicLeadIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/new': {
      id: '/_authenticated/sites/new'
      path: '/sites/new'
      fullPath: '/sites/new'
      preLoaderRoute: typeof AuthenticatedSitesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/tone-profile': {
      id: '/_authenticated/settings/tone-profile'
      path: '/settings/tone-profile'
      fullPath: '/settings/tone-profile'
      preLoaderRoute: typeof AuthenticatedSettingsToneProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/growth-goal': {
      id: '/_authenticated/settings/growth-goal'
      path: '/settings/growth-goal'
      fullPath: '/settings/growth-goal'
      preLoaderRoute: typeof AuthenticatedSettingsGrowthGoalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/business-profile': {
      id: '/_authenticated/settings/business-profile'
      path: '/settings/business-profile'
      fullPath: '/settings/business-profile'
      preLoaderRoute: typeof AuthenticatedSettingsBusinessProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/welcome': {
      id: '/_authenticated/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthenticatedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/site': {
      id: '/_authenticated/onboarding/site'
      path: '/site'
      fullPath: '/onboarding/site'
      preLoaderRoute: typeof AuthenticatedOnboardingSiteRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/done': {
      id: '/_authenticated/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AuthenticatedOnboardingDoneRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/business': {
      id: '/_authenticated/onboarding/business'
      path: '/business'
      fullPath: '/onboarding/business'
      preLoaderRoute: typeof AuthenticatedOnboardingBusinessRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/growth/reports': {
      id: '/_authenticated/growth/reports'
      path: '/growth/reports'
      fullPath: '/growth/reports'
      preLoaderRoute: typeof AuthenticatedGrowthReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/monthly-plan': {
      id: '/_authenticated/growth/monthly-plan'
      path: '/growth/monthly-plan'
      fullPath: '/growth/monthly-plan'
      preLoaderRoute: typeof AuthenticatedGrowthMonthlyPlanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/masterplan': {
      id: '/_authenticated/growth/masterplan'
      path: '/growth/masterplan'
      fullPath: '/growth/masterplan'
      preLoaderRoute: typeof AuthenticatedGrowthMasterplanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/leads': {
      id: '/_authenticated/growth/leads'
      path: '/growth/leads'
      fullPath: '/growth/leads'
      preLoaderRoute: typeof AuthenticatedGrowthLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/intelligence': {
      id: '/_authenticated/growth/intelligence'
      path: '/growth/intelligence'
      fullPath: '/growth/intelligence'
      preLoaderRoute: typeof AuthenticatedGrowthIntelligenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/gbp': {
      id: '/_authenticated/growth/gbp'
      path: '/growth/gbp'
      fullPath: '/growth/gbp'
      preLoaderRoute: typeof AuthenticatedGrowthGbpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/flow': {
      id: '/_authenticated/growth/flow'
      path: '/growth/flow'
      fullPath: '/growth/flow'
      preLoaderRoute: typeof AuthenticatedGrowthFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/execution': {
      id: '/_authenticated/growth/execution'
      path: '/growth/execution'
      fullPath: '/growth/execution'
      preLoaderRoute: typeof AuthenticatedGrowthExecutionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/blueprint': {
      id: '/_authenticated/growth/blueprint'
      path: '/growth/blueprint'
      fullPath: '/growth/blueprint'
      preLoaderRoute: typeof AuthenticatedGrowthBlueprintRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$tenantId': {
      id: '/_authenticated/clients/$tenantId'
      path: '/clients/$tenantId'
      fullPath: '/clients/$tenantId'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits/$auditId': {
      id: '/_authenticated/audits/$auditId'
      path: '/audits/$auditId'
      fullPath: '/audits/$auditId'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$tenantId/': {
      id: '/_authenticated/clients/$tenantId/'
      path: '/'
      fullPath: '/clients/$tenantId/'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/api/public/wpcom/callback': {
      id: '/api/public/wpcom/callback'
      path: '/api/public/wpcom/callback'
      fullPath: '/api/public/wpcom/callback'
      preLoaderRoute: typeof ApiPublicWpcomCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sites/$siteId/inventory': {
      id: '/_authenticated/sites/$siteId/inventory'
      path: '/sites/$siteId/inventory'
      fullPath: '/sites/$siteId/inventory'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdInventoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites/$siteId/audits': {
      id: '/_authenticated/sites/$siteId/audits'
      path: '/sites/$siteId/audits'
      fullPath: '/sites/$siteId/audits'
      preLoaderRoute: typeof AuthenticatedSitesSiteIdAuditsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$tenantId/settings': {
      id: '/_authenticated/clients/$tenantId/settings'
      path: '/settings'
      fullPath: '/clients/$tenantId/settings'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdSettingsRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/clients/$tenantId/reports': {
      id: '/_authenticated/clients/$tenantId/reports'
      path: '/reports'
      fullPath: '/clients/$tenantId/reports'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdReportsRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/clients/$tenantId/pages': {
      id: '/_authenticated/clients/$tenantId/pages'
      path: '/pages'
      fullPath: '/clients/$tenantId/pages'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdPagesRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/clients/$tenantId/overview': {
      id: '/_authenticated/clients/$tenantId/overview'
      path: '/overview'
      fullPath: '/clients/$tenantId/overview'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdOverviewRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/clients/$tenantId/leads': {
      id: '/_authenticated/clients/$tenantId/leads'
      path: '/leads'
      fullPath: '/clients/$tenantId/leads'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdLeadsRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/clients/$tenantId/execution': {
      id: '/_authenticated/clients/$tenantId/execution'
      path: '/execution'
      fullPath: '/clients/$tenantId/execution'
      preLoaderRoute: typeof AuthenticatedClientsTenantIdExecutionRouteImport
      parentRoute: typeof AuthenticatedClientsTenantIdRoute
    }
    '/_authenticated/audits/$auditId_/proposals': {
      id: '/_authenticated/audits/$auditId_/proposals'
      path: '/audits/$auditId/proposals'
      fullPath: '/audits/$auditId/proposals'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audits/$auditId_/compare': {
      id: '/_authenticated/audits/$auditId_/compare'
      path: '/audits/$auditId/compare'
      fullPath: '/audits/$auditId/compare'
      preLoaderRoute: typeof AuthenticatedAuditsAuditIdCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/growth/masterplan_/$itemId/proposals': {
      id: '/_authenticated/growth/masterplan_/$itemId/proposals'
      path: '/growth/masterplan/$itemId/proposals'
      fullPath: '/growth/masterplan/$itemId/proposals'
      preLoaderRoute: typeof AuthenticatedGrowthMasterplanItemIdProposalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingBusinessRoute: typeof AuthenticatedOnboardingBusinessRoute
  AuthenticatedOnboardingDoneRoute: typeof AuthenticatedOnboardingDoneRoute
  AuthenticatedOnboardingSiteRoute: typeof AuthenticatedOnboardingSiteRoute
  AuthenticatedOnboardingWelcomeRoute: typeof AuthenticatedOnboardingWelcomeRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingBusinessRoute: AuthenticatedOnboardingBusinessRoute,
    AuthenticatedOnboardingDoneRoute: AuthenticatedOnboardingDoneRoute,
    AuthenticatedOnboardingSiteRoute: AuthenticatedOnboardingSiteRoute,
    AuthenticatedOnboardingWelcomeRoute: AuthenticatedOnboardingWelcomeRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedClientsTenantIdRouteChildren {
  AuthenticatedClientsTenantIdExecutionRoute: typeof AuthenticatedClientsTenantIdExecutionRoute
  AuthenticatedClientsTenantIdLeadsRoute: typeof AuthenticatedClientsTenantIdLeadsRoute
  AuthenticatedClientsTenantIdOverviewRoute: typeof AuthenticatedClientsTenantIdOverviewRoute
  AuthenticatedClientsTenantIdPagesRoute: typeof AuthenticatedClientsTenantIdPagesRoute
  AuthenticatedClientsTenantIdReportsRoute: typeof AuthenticatedClientsTenantIdReportsRoute
  AuthenticatedClientsTenantIdSettingsRoute: typeof AuthenticatedClientsTenantIdSettingsRoute
  AuthenticatedClientsTenantIdIndexRoute: typeof AuthenticatedClientsTenantIdIndexRoute
}

const AuthenticatedClientsTenantIdRouteChildren: AuthenticatedClientsTenantIdRouteChildren =
  {
    AuthenticatedClientsTenantIdExecutionRoute:
      AuthenticatedClientsTenantIdExecutionRoute,
    AuthenticatedClientsTenantIdLeadsRoute:
      AuthenticatedClientsTenantIdLeadsRoute,
    AuthenticatedClientsTenantIdOverviewRoute:
      AuthenticatedClientsTenantIdOverviewRoute,
    AuthenticatedClientsTenantIdPagesRoute:
      AuthenticatedClientsTenantIdPagesRoute,
    AuthenticatedClientsTenantIdReportsRoute:
      AuthenticatedClientsTenantIdReportsRoute,
    AuthenticatedClientsTenantIdSettingsRoute:
      AuthenticatedClientsTenantIdSettingsRoute,
    AuthenticatedClientsTenantIdIndexRoute:
      AuthenticatedClientsTenantIdIndexRoute,
  }

const AuthenticatedClientsTenantIdRouteWithChildren =
  AuthenticatedClientsTenantIdRoute._addFileChildren(
    AuthenticatedClientsTenantIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
  AuthenticatedAuditsAuditIdRoute: typeof AuthenticatedAuditsAuditIdRoute
  AuthenticatedClientsTenantIdRoute: typeof AuthenticatedClientsTenantIdRouteWithChildren
  AuthenticatedGrowthBlueprintRoute: typeof AuthenticatedGrowthBlueprintRoute
  AuthenticatedGrowthExecutionRoute: typeof AuthenticatedGrowthExecutionRoute
  AuthenticatedGrowthFlowRoute: typeof AuthenticatedGrowthFlowRoute
  AuthenticatedGrowthGbpRoute: typeof AuthenticatedGrowthGbpRoute
  AuthenticatedGrowthIntelligenceRoute: typeof AuthenticatedGrowthIntelligenceRoute
  AuthenticatedGrowthLeadsRoute: typeof AuthenticatedGrowthLeadsRoute
  AuthenticatedGrowthMasterplanRoute: typeof AuthenticatedGrowthMasterplanRoute
  AuthenticatedGrowthMonthlyPlanRoute: typeof AuthenticatedGrowthMonthlyPlanRoute
  AuthenticatedGrowthReportsRoute: typeof AuthenticatedGrowthReportsRoute
  AuthenticatedSettingsBusinessProfileRoute: typeof AuthenticatedSettingsBusinessProfileRoute
  AuthenticatedSettingsGrowthGoalRoute: typeof AuthenticatedSettingsGrowthGoalRoute
  AuthenticatedSettingsToneProfileRoute: typeof AuthenticatedSettingsToneProfileRoute
  AuthenticatedSitesNewRoute: typeof AuthenticatedSitesNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedSitesIndexRoute: typeof AuthenticatedSitesIndexRoute
  AuthenticatedAuditsAuditIdCompareRoute: typeof AuthenticatedAuditsAuditIdCompareRoute
  AuthenticatedAuditsAuditIdProposalsRoute: typeof AuthenticatedAuditsAuditIdProposalsRoute
  AuthenticatedSitesSiteIdAuditsRoute: typeof AuthenticatedSitesSiteIdAuditsRoute
  AuthenticatedSitesSiteIdInventoryRoute: typeof AuthenticatedSitesSiteIdInventoryRoute
  AuthenticatedGrowthMasterplanItemIdProposalsRoute: typeof AuthenticatedGrowthMasterplanItemIdProposalsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
  AuthenticatedAuditsAuditIdRoute: AuthenticatedAuditsAuditIdRoute,
  AuthenticatedClientsTenantIdRoute:
    AuthenticatedClientsTenantIdRouteWithChildren,
  AuthenticatedGrowthBlueprintRoute: AuthenticatedGrowthBlueprintRoute,
  AuthenticatedGrowthExecutionRoute: AuthenticatedGrowthExecutionRoute,
  AuthenticatedGrowthFlowRoute: AuthenticatedGrowthFlowRoute,
  AuthenticatedGrowthGbpRoute: AuthenticatedGrowthGbpRoute,
  AuthenticatedGrowthIntelligenceRoute: AuthenticatedGrowthIntelligenceRoute,
  AuthenticatedGrowthLeadsRoute: AuthenticatedGrowthLeadsRoute,
  AuthenticatedGrowthMasterplanRoute: AuthenticatedGrowthMasterplanRoute,
  AuthenticatedGrowthMonthlyPlanRoute: AuthenticatedGrowthMonthlyPlanRoute,
  AuthenticatedGrowthReportsRoute: AuthenticatedGrowthReportsRoute,
  AuthenticatedSettingsBusinessProfileRoute:
    AuthenticatedSettingsBusinessProfileRoute,
  AuthenticatedSettingsGrowthGoalRoute: AuthenticatedSettingsGrowthGoalRoute,
  AuthenticatedSettingsToneProfileRoute: AuthenticatedSettingsToneProfileRoute,
  AuthenticatedSitesNewRoute: AuthenticatedSitesNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedSitesIndexRoute: AuthenticatedSitesIndexRoute,
  AuthenticatedAuditsAuditIdCompareRoute:
    AuthenticatedAuditsAuditIdCompareRoute,
  AuthenticatedAuditsAuditIdProposalsRoute:
    AuthenticatedAuditsAuditIdProposalsRoute,
  AuthenticatedSitesSiteIdAuditsRoute: AuthenticatedSitesSiteIdAuditsRoute,
  AuthenticatedSitesSiteIdInventoryRoute:
    AuthenticatedSitesSiteIdInventoryRoute,
  AuthenticatedGrowthMasterplanItemIdProposalsRoute:
    AuthenticatedGrowthMasterplanItemIdProposalsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  RShareTokenRoute: RShareTokenRoute,
  ApiPublicLeadIngestRoute: ApiPublicLeadIngestRoute,
  ApiPublicRunAnalyzerJobRoute: ApiPublicRunAnalyzerJobRoute,
  ApiPublicWpcomCallbackRoute: ApiPublicWpcomCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
