-- Monthly Report Share Link V1
-- Add share_token to monthly_reports.
-- Token is a 32-char hex generated by the server, never by the DB.
-- Public route fetches by token via service_role — no broad public RLS needed.

ALTER TABLE public.monthly_reports
  ADD COLUMN IF NOT EXISTS share_token text UNIQUE,
  ADD COLUMN IF NOT EXISTS share_token_created_at timestamptz;

COMMENT ON COLUMN public.monthly_reports.share_token IS
  '32-char hex public share token. NULL = not shared. Set via server function.';
