-- Client portal token — added to tenants table.
-- Operators generate a long-lived token once; clients use the URL to access
-- their read-only growth dashboard at /portal/:portalToken.
-- Same pattern as monthly_reports.share_token — service_role lookup only.

ALTER TABLE public.tenants
  ADD COLUMN IF NOT EXISTS portal_token TEXT UNIQUE,
  ADD COLUMN IF NOT EXISTS portal_token_created_at TIMESTAMPTZ;

-- Index for fast token lookup on the public portal endpoint.
CREATE INDEX IF NOT EXISTS idx_tenants_portal_token
  ON public.tenants (portal_token)
  WHERE portal_token IS NOT NULL;

COMMENT ON COLUMN public.tenants.portal_token IS
  'Long-lived access token for the client-facing portal (/portal/:token). Generated by operator. Revocable.';
COMMENT ON COLUMN public.tenants.portal_token_created_at IS
  'When the current portal token was generated.';
